### ISSUE TITLE
New packet/seqno appended to last received in receiving window 

### ISSUE THREAD

**Issue by JustinLovesCompsci** [JustinLovesCompsci/Network_Protocol#9]
New packet or seqno appended to last received in receiving window without calling append_node_to_last_received. 

In process_received_data_pkt, on line ~327, the seqno_last_received is always the same as the newly arrived packet's seqno after the second message before appending the new packet to the last received linked list.

**Comment by stevenyy** [comment]
for clarification, in process_received_data_pkt, seqnoLastReceived should not have the same value with p->receiving_window->last_packet_received->packet->seqno because the packet has not been appended yet.

![screen shot 2015-04-06 at 3 06 35 pm](https://cloud.githubusercontent.com/assets/4335998/7010369/9668d680-dc6e-11e4-8c85-b02b0e1b11bc.png)

**Comment by lawrencelin** [comment]
Fixed.
